namespace ConquestFrontierWarsRay.Data.Models.BT;

public enum LAUNCHCLASS : uint {
	LC_INVALID = 0,
	LC_TURRET = 1,
	LC_VERTICLE_LAUNCH = 2,
	LC_MISSILE = 3,
	LC_AIR_DEFENSE = 4,
	LC_MINELAYER = 5,
	LC_FIGHTER_WING = 6,
	LC_KAMIKAZE_WING = 7,
	LC_SHIPLAUNCH = 8,
	LC_FANCY_LAUNCH = 9,
	LC_CLOAK_LAUNCH = 10,
	LC_RECON_LAUNCH = 11,
	LC_WORMHOLE_LAUNCH = 12,
	LC_PING_LAUNCH = 13,
	LC_MULTICLOAK_LAUNCH = 14,
	LC_TALORIAN_LAUNCH = 15,
	LC_JUMP_LAUNCH = 16,
	LC_ARTILERY_LAUNCH = 17,
	LC_BUFF_LAUNCHER = 18,
	LC_TRACTOR_WAVE_LAUNCH = 19,
	LC_BARRAGE_LAUNCH = 20,
	LC_REPAIR_LAUNCH = 21,
	LC_MOON_RESOURCE_LAUNCH = 22,
	LC_SYSTEM_BUFF_LAUNCHER = 23,
	LC_NOVA_LAUNCH = 24,
	LC_TEMPHQ_LAUNCHER = 25,
	LC_ARTIFACT_LAUNCHER = 26,
	LC_EFFECT_LAUNCHER = 27
}

public enum WPNCLASS : uint {
	WPN_INVALID = 0,
	WPN_MISSILE = 1,
	WPN_BOLT = 2,
	WPN_BEAM = 3,
	WPN_ARC = 4,
	WPN_AUTOCANNON = 5,
	WPN_SPECIALBOLT = 6,
	WPN_TRACTOR = 7,
	WPN_OVERDRIVE = 8,
	WPN_REPULSOR = 9,
	WPN_SWAPPER = 10,
	WPN_PLASMABOLT = 11,
	WPN_ANMBOLT = 12,
	WPN_AEBOLT = 13,
	WPN_AEGIS = 14,
	WPN_MIMIC = 15,
	WPN_ZEALOT = 16,
	WPN_STASISBOLT = 17,
	WPN_REPELLENTCLOUD = 18,
	WPN_SYNTHESIS = 19,
	WPN_MASS_DISRUPTOR = 20,
	WPN_DESTABILIZER = 21,
	WPN_GATTLINGBEAM = 22,
	WPN_LASERSPRAY = 23,
	WPN_WORMHOLE = 24,
	WPN_REPULSORWAVE = 25,
	WPN_DUMBRECONPROBE = 26,
	WPN_SPACEWAVE = 27,
	WPN_PKBOLT = 28,
	WPN_ART_BUFF = 29,
	WPN_ART_LISTEN = 30,
	WPN_ART_TERRAFORM = 31
}

public enum FIELDCLASS : uint {
	FC_INVALID = 0,
	FC_ASTEROIDFIELD = 1,
	FC_MINEFIELD = 2,
	FC_NEBULA = 3,
	FC_ANTIMATTER = 4
}

public enum SPACESHIPCLASS : uint {
	SSC_INVALID = 0,
	SSC_GUNBOAT = 1,
	SSC_BUILDSHIP = 2,
	SSC_HARVESTSHIP = 3,
	SSC_FABRICATOR = 4,
	SSC_MINELAYER = 5,
	SSC_RECONPROBE = 6,
	SSC_TORPEDO = 7,
	SSC_GUNSAT = 8,
	SSC_FLAGSHIP = 9,
	SSC_SUPPLYSHIP = 10,
	SSC_TROOPSHIP = 11,
	SSC_RECOVERYSHIP = 12,
	SSC_SPIDERDRONE = 13,
	SSC_TERRANDRONE = 14
}

public enum BUILDOBJCLASS : uint {
	BO_TERRAN = 0,
	BO_MANTIS = 1,
	BO_SOLARIAN = 2,
	BO_VYRIUM = 3
}

public enum ARMOR_TYPE : uint {
	NO_ARMOR = 0,
	LIGHT_ARMOR = 1,
	MEDIUM_ARMOR = 2,
	HEAVY_ARMOR = 3
}

public enum EFFECTCLASS : uint {
	FX_INVALID = 0,
	FX_FIREBALL = 1,
	FX_PARTICLE = 2,
	FX_STREAK = 3,
	FX_SPARK = 4,
	FX_ANIMOBJ = 5,
	FX_CLOAKEFFECT = 6,
	FX_ENGINETRAIL = 7,
	FX_WORMHOLE_BLAST = 8,
	FX_TALORIAN_EFFECT = 9,
	FX_TROOPPOD = 10,
	FX_PARTICLE_CIRCLE = 11,
	FX_NOVA_EXPLOSION = 12
}

public enum UNIT_SPECIAL_ABILITY : uint {
	USA_NONE = 0,
	USA_ASSAULT = 1,
	USA_TEMPEST = 2,
	USA_PROBE = 3,
	USA_CLOAK = 4,
	USA_AEGIS = 5,
	USA_VAMPIRE = 6,
	USA_STASIS = 7,
	USA_FURYRAM = 8,
	USA_REPEL = 9,
	USA_BOMBER = 10,
	USA_MIMIC = 11,
	USA_MINELAYER = 12,
	USA_S_MINELAYER = 13,
	USA_REPULSOR = 14,
	USA_SYNTHESIS = 15,
	USA_MASS_DISRUPTOR = 16,
	USA_DESTABILIZER = 17,
	USA_WORMHOLE = 18,
	USA_PING = 19,
	USA_M_PING = 20,
	USA_S_PING = 21,
	USA_MULTICLOAK = 22,
	USA_TRACTOR = 23,
	USA_JUMP = 24,
	USA_ARTILERY = 25,
	USA_TRACTOR_WAVE = 26,
	USA_NOVA = 27,
	USA_SHIELD_JAM = 28,
	USA_WEAPON_JAM = 29,
	USA_SENSOR_JAM = 30,
	USA_DOCK = 31,
	USA_LAST = 32
}

public enum MINETYPE : uint {
	MINETYPE_UNKOWN = 0,
	MINETYPE_UNKNOWN = 0,
	MINETYPE_SPINE = 1
}

public enum M_RESOURCE_TYPE : uint {
	M_GAS = 0,
	M_METAL = 1,
	M_CREW = 2,
	M_COMMANDPTS = 3
}

public enum M_NUGGET_TYPE : uint {
	M_GAS_NUGGETS = 0,
	M_METAL_NUGGET = 1,
	M_SCRAP_NUGGET = 2,
	M_HYADES_NUGGET = 3
}

public enum BT_SYSTEM_BUFF_TYPE : uint {
	INTEL_CENTER_EFFECT = 0
}

public enum BT_SYSTEM_BUFF_TARGET_TYPE : uint {
	ALL_PLAYERS = 0,
	ALLIES_ONLY = 1,
	ENEMIES_ONLY = 2
}

public enum BT_NEBTYPE : uint {
	NEB_ION = 0,
	NEB_ANTIMATTER = 1,
	NEB_HELIOUS = 2,
	NEB_LITHIUM = 3,
	NEB_HYADES = 4,
	NEB_CELSIUS = 5,
	NEB_CYGNUS = 6
}

public enum PLANET_TYPE : uint {
	M_CLASS = 0,
	METAL_PLANET = 1,
	GAS_PLANET = 2,
	OTHER_PLANET = 3
}

public enum PLATFORMCLASS : uint {
	PC_OLDSTYLE = 0,
	PC_GUNPLAT = 1,
	PC_SUPPLYPLAT = 2,
	PC_BUILDPLAT = 3,
	PC_REPAIRPLAT = 4,
	PC_REFINERY = 5,
	PC_GENERAL = 6,
	PC_BUILDSUPPLAT = 7,
	PC_JUMPPLAT = 8,
	PC_SELL = 9
}

public enum RESEARCH_TYPE : uint {
	RESEARCH_TECH = 0,
	RESEARCH_UPGRADE = 1,
	RESEARCH_ADMIRAL = 2,
	RESEARCH_COMMAND_KIT = 3
}

public enum RESEARCH_SUBTITLE : uint {
	NO_SUBTITLE = 0,
	SUB_RES_MIMIC = 4530,
	SUB_RES_ENGINE = 4531,
	SUB_RES_FIGHTER = 4532,
	SUB_RES_GRAVWELL = 4533,
	SUB_RES_HULL = 4534,
	SUB_RES_LEECH = 4535,
	SUB_RES_RAM = 4536,
	SUB_RES_REPCLOUD = 4537,
	SUB_RES_REP_WAVE = 4538,
	SUB_RES_SENSOR = 4539,
	SUB_RES_SHIELD = 4540,
	SUB_RES_SUPPLY = 4541,
	SUB_RES_SIPHON = 4542,
	SUB_RES_RESUPPLY = 4543,
	SUB_RES_WEAPON = 4544,
	SUB_RES_SHROUD = 4545,
	SUB_RES_DESTABILIZER = 4546,
	SUB_RES_GAS = 4547,
	SUB_RES_LEGIONAIRE = 4548,
	SUB_RES_MASS_DISRUPTOR = 4549,
	SUB_RES_ORE = 4550,
	SUB_RES_PROTEUS = 4551,
	SUB_RES_SYNTH = 4552,
	SUB_RES_GALIOT = 4553,
	SUB_RES_AUGER = 4554,
	SUB_RES_TEMPEST = 4555,
	SUB_RES_PROBE = 4556,
	SUB_RES_AEGIS = 4557,
	SUB_RES_VAMP = 4558,
	SUB_RES_CLOAK = 4559,
	SUB_RES_MISSILE = 4560,
	SUB_RES_HARVESTER = 4561,
	SUB_RES_TROOPSHIP = 4562,
	SUB_UPGRADE = 4563
}

public enum RELATIVE_TYPE : uint {
	RT_CENTER = 0,
	RT_GROUP = 1
}

public enum RELATION : uint {
	RE_EDGE = 0,
	RE_CENTER = 1
}

public enum PLACEMENT_TYPE : uint {
	PT_NORMAL = 0,
	PT_LINE = 1,
	PT_LINE_END = 2,
	PT_V = 3
}

public enum AI_TYPE : uint {
	NORMAL = 0,
	ROVER = 1,
	SPOTTER = 2,
	STRIKER = 3
}

public enum FORMATION_CLOAK_USAGE : uint {
	CU_NONE = 0,
	CU_ALL = 1,
	CU_RECON_ONLY = 2,
	CU_RECON_AND_SPOTTERS = 3
}

public enum TRIGGER_TYPE : uint {
	SPHERE = 0,
	REGION = 1,
	LINE = 2
}

public enum MAP_DMAP_FUNC : uint {
	LINEAR = 0,
	LESS_IS_LIKELY = 1,
	MORE_IS_LIKELY = 2
}

public enum MAP_PLACEMENT : uint {
	RANDOM = 0,
	CLUSTER = 1,
	PLANET_RING = 2,
	STREAKS = 3,
	SPOTS = 4
}

public enum MAP_OVERLAP : uint {
	NO_OVERLAP = 0,
	LEVEL1 = 1,
	LEVEL2 = 2
}

public enum MAP_SECTOR_SIZE : uint {
	SMALL_SIZE = 1,
	MEDIUM_SIZE = 2,
	LARGE_SIZE = 4,
	S_M_SIZE = 3,
	S_L_SIZE = 5,
	M_L_SIZE = 6,
	ALL_SIZE = 7
}

public enum MAP_SECTOR_FORMATION : uint {
	SF_RANDOM = 0,
	SF_RING = 1,
	SF_DOUBLERING = 2,
	SF_STAR = 3,
	SF_INRING = 4,
	SF_MULTI_RANDOM = 5
}

public enum MAP_MACRO_OPERATION : uint {
	MC_PLACE_HABITABLE_PLANET = 0,
	MC_PLACE_GAS_PLANET = 1,
	MC_PLACE_METAL_PLANET = 2,
	MC_PLACE_OTHER_PLANET = 3,
	MC_PLACE_TERRAIN = 4,
	MC_PLACE_PLAYER_BOMB = 5,
	MC_MARK_RING = 6
}

public enum SFX_ID : uint {
	INVALID = 0,
	BUTTONPRESS1 = 1,
	BUTTONPRESS2 = 2,
	IN_RANGE = 3,
	START_CONSTRUCTION = 4,
	END_CONSTRUCTION = 5,
	ZERO_MONEY = 6,
	LIGHTINDUSTRY_BUTTON = 7,
	HEAVYINDUSTRY_BUTTON = 8,
	HITECHINDUSTRY_BUTTON = 9,
	HQ_BUTTON = 10,
	RESEARCH_BUTTON = 11,
	PLANET_DEPLETED = 12,
	HARVEST_REDEPLOY = 13,
	RESEARCH_COMPLETED = 14,
	JG_ENTER1 = 15,
	JG_ENTER2 = 16,
	JG_ARRIVE1 = 17,
	JG_ARRIVE2 = 18,
	JG_AMBIENCE = 19,
	T_ARC_CANNON = 20,
	T_DEFENSEGUN1 = 21,
	T_SHIELDHIT = 22,
	T_SHIELDFIZZOUT = 23,
	T_SHIELDFIZZIN = 24,
	T_LASERTURRET_SML = 25,
	T_CORVETTE_IMPACT = 26,
	T_LASERTURRET_MED = 27,
	T_LASERTURRET_LGE = 28,
	T_MISSILE = 29,
	T_FLYBY1 = 30,
	T_FIGHTERFLYBY1 = 31,
	T_FIGHTERFLYBY2 = 32,
	T_FIGHTERFLYBY3 = 33,
	T_FIGHTERFLYBY4 = 34,
	T_FIGHTERLAUNCH1 = 35,
	T_FIGHTERLAUNCH2 = 36,
	T_FIGHTERLAUNCH3 = 37,
	T_FIGHTERLAUNCH4 = 38,
	T_CONSTRUCTION = 39,
	T_POWERUP = 40,
	T_LSATFIRE = 41,
	T_LSATDEPLOY = 42,
	T_FIGHTEREXPLO = 43,
	T_HARVESTERUNLOAD = 44,
	T_IMPACTCORVETTE = 45,
	T_IMPACTLSAT = 46,
	T_TROOPRELEASE = 47,
	T_IMPACTMISSILE = 48,
	T_IMPACTFIGHTER = 49,
	T_FIGHTERFIRE1 = 50,
	T_FIGHTERFIRE2 = 51,
	T_FIGHTERFIRE3 = 52,
	T_FIGHTERFIRE4 = 53,
	T_PROBELAUNCH = 54,
	T_FIGHTERKAMIKAZE = 55,
	T_TEMPESTLAUNCH = 56,
	T_IMPACTDREADNOUGHT = 57,
	T_GRAVWELL = 58,
	T_TRACTORDEBRIS = 59,
	T_PROBEFIZZLE = 60,
	T_AEGISSHIELD = 61,
	T_IONCHARGE = 62,
	T_TROOPASSAULT = 63,
	M_FIGHTERLAUNCH1 = 64,
	M_FIGHTERLAUNCH2 = 65,
	M_FIGHTERLAUNCH3 = 66,
	M_FIGHTERLAUNCH4 = 67,
	M_FIGHTERFLYBY1 = 68,
	M_FIGHTERFLYBY2 = 69,
	M_FIGHTERFLYBY3 = 70,
	M_FIGHTERFLYBY4 = 71,
	M_PLASMASMALL = 72,
	M_PLASMAMED = 73,
	M_CONSTRUCTION = 74,
	M_FIGHTERBLAST = 75,
	M_PLASMACHARGE = 76,
	M_SELLINGUNIT = 77,
	M_SHIELDHIT = 78,
	M_REPELLCLOUD = 79,
	S_CONSTRUCTION = 80,
	S_BALLENERGY = 81,
	S_BEAM_LG = 82,
	S_BEAM_MED = 83,
	S_DESTABILIZER = 84,
	S_DISRUPTORDAM = 85,
	S_ECLIPSE = 86,
	S_FORGERDEPLOY = 87,
	S_LAUNCHDESTAB = 88,
	S_LAUNCHDISRUP = 89,
	S_LEGIONAIRE = 90,
	S_LEGIONSUCCESS = 91,
	S_MINELAYER = 92,
	S_REPULSOR = 93,
	S_SELLINGUNIT = 94,
	S_STRATUM = 95,
	S_SYNTHESIS = 96,
	S_UNLOAD = 97,
	S_BEAM_MED2 = 98,
	S_SHIELDHIT = 99,
	S_BEAM_SML = 100,
	NEBULA_ION = 101,
	NEBULA_IONSPARK = 102,
	NEBULA_PLASMA = 103,
	NEBULA_ARGON = 104,
	NEBULA_HELIOUS = 105,
	NEBULA_HYADES = 106,
	ASTEROID_FIELD = 107,
	NEBULA_CELSIUS = 108,
	NEBULA_CYGNUS = 109,
	NEBULA_LITHIUM = 110
}
