from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
SRC = ROOT / "src"
CONQUEST = ROOT / "src" / "Conquest"
OUT = ROOT / "ConquestFrontierWarsRay" / "src" / "Gloabls"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*", "", text)
    return text


def parse_enum_block(text: str, enum_name: str) -> list[tuple[str, str | None]]:
    pattern = re.compile(rf"enum\s+{re.escape(enum_name)}\s*\{{(.*?)\}};", re.S)
    match = pattern.search(text)
    if not match:
        raise RuntimeError(f"enum {enum_name} not found")

    body = strip_comments(match.group(1))
    items: list[tuple[str, str | None]] = []
    for raw_item in body.split(","):
        item = raw_item.strip()
        if not item:
            continue
        if "=" in item:
            name, value = [part.strip() for part in item.split("=", 1)]
            items.append((name, value))
        else:
            items.append((item, None))
    return items


def emit_enum(enum_name: str, underlying_type: str, items: list[tuple[str, str | None]]) -> list[str]:
    lines = [f"public enum {enum_name} : {underlying_type} {{"]
    for name, value in items:
        if value is None:
            lines.append(f"\t{name},")
        else:
            lines.append(f"\t{name} = {value},")
    lines.append("}")
    return lines


def parse_defines(text: str, prefix: str) -> list[tuple[str, str]]:
    items: list[tuple[str, str]] = []
    for line in strip_comments(text).splitlines():
        line = line.strip()
        if not line.startswith("#define "):
            continue
        parts = line.split(None, 2)
        if len(parts) < 3:
            continue
        name = parts[1]
        if not name.startswith(prefix):
            continue
        value = parts[2].strip()
        items.append((name, value))
    return items


def emit_define_enum(enum_name: str, underlying_type: str, items: list[tuple[str, str]]) -> list[str]:
    lines = [f"public enum {enum_name} : {underlying_type} {{"]
    for name, value in items:
        lines.append(f"\t{name} = {value},")
    lines.append("}")
    return lines


def parse_rgb_array(text: str, array_name: str) -> list[list[int]]:
    pattern = re.compile(rf"{re.escape(array_name)}\[[^\]]+\].*?\{{(.*?)\}};", re.S)
    match = pattern.search(text)
    if not match:
        raise RuntimeError(f"array {array_name} not found")
    body = strip_comments(match.group(1))
    rgb_pattern = re.compile(r"RGB\((\d+),\s*(\d+),\s*(\d+)\)")
    return [[int(r), int(g), int(b)] for r, g, b in rgb_pattern.findall(body)]


def main() -> None:
    globals_header = read_text(CONQUEST / "Include" / "Globals.h")
    mission_header = read_text(ROOT / "DInclude" / "DMissionEnum.h")

    generated_dir = OUT / "Generated"
    resource_dir = OUT / "Resources"
    generated_dir.mkdir(parents=True, exist_ok=True)
    resource_dir.mkdir(parents=True, exist_ok=True)

    namespace = "ConquestFrontierWarsRay.Globals"

    mission_lines = ["// <auto-generated />", f"namespace {namespace};", ""]
    mission_lines.extend(emit_enum("MRace", "int", parse_enum_block(mission_header, "M_RACE")))
    mission_lines.append("")
    mission_lines.extend(emit_enum("MResourceType", "int", parse_enum_block(mission_header, "M_RESOURCE_TYPE")))
    mission_lines.append("")
    mission_lines.extend(emit_enum("MObjClass", "int", parse_enum_block(mission_header, "M_OBJCLASS")))
    mission_lines.append("")
    mission_output = "\n".join(mission_lines)
    (generated_dir / "LegacyMissionEnums.g.cs").write_text(mission_output, encoding="utf-8")

    globals_lines = ["// <auto-generated />", f"namespace {namespace};", ""]
    globals_lines.extend(emit_define_enum("ConquestEventCode", "uint", parse_defines(globals_header, "CQE_")))
    globals_lines.append("")
    globals_lines.extend(emit_enum("PacketType", "int", parse_enum_block(globals_header, "PACKET_TYPE")))
    globals_lines.append("")
    globals_output = "\n".join(globals_lines)
    (generated_dir / "LegacyGlobalsContracts.g.cs").write_text(globals_output, encoding="utf-8")

    manifest = {
        "screenHIdealWidth": 1024,
        "screenHIdealHeight": 768,
        "defaultColorTable": parse_rgb_array(globals_header, "DEFCOLORTABLE"),
        "sectorColorTable": parse_rgb_array(globals_header, "SECTORCOLORTABLE"),
    }
    (resource_dir / "globals-resource-manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
