<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ConquestFrontierWarsRay</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fonts\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="src\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Remove="src\**\*" />
    <EmbeddedResource Remove="tests\**\*" />
    <None Include="src\**\*" Exclude="src\**\bin\**;src\**\obj\**" />
    <None Include="tests\**\*" Exclude="tests\**\bin\**;tests\**\obj\**" />
  </ItemGroup>
</Project>
