using System.Xml.Linq;
using ConquestFrontierWarsRay.Data.Models;
using ConquestFrontierWarsRay.Data.Models.BT;
using ConquestFrontierWarsRay.Data.UtfDb.Models;

namespace ConquestFrontierWarsRay.Data.UtfDb.Types;

internal static class BTBatch2TypeParserSupport {
	public static UtfDbField Annotate(UtfDbField field) {
		return field.Label switch {
			"base.obj_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((OBJCLASS)uint.Parse(field.Value)) },
			"base.b_edit_dropable" => field with { EnumValue = UtfDbTypeParserHelpers.FormatBoolean(uint.Parse(field.Value) != 0) },
			"type.type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((LAUNCHCLASS)uint.Parse(field.Value)) },
			"wpn_class.wpn_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((WPNCLASS)uint.Parse(field.Value)) },
			"fx_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((EFFECTCLASS)uint.Parse(field.Value)) },
			"base_field_data.field_class" or "field_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((FIELDCLASS)uint.Parse(field.Value)) },
			"armor_data.my_armor" or "mission_data.armor_data.my_armor" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((ARMOR_TYPE)uint.Parse(field.Value)) },
			"ambient_sfx" or "launch_sfx" or "kamikaze_yell" or "fighterwhoosh" or "fighter_launch" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((SFX_ID)uint.Parse(field.Value)) },
			"mine_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((MINETYPE)uint.Parse(field.Value)) },
			"special_ability" or "mission_data.special_ability" or "mission_data.special_ability1" or "mission_data.special_ability2" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((UNIT_SPECIAL_ABILITY)uint.Parse(field.Value)) },
			"buff_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((BT_SYSTEM_BUFF_TYPE)uint.Parse(field.Value)) },
			"target_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((BT_SYSTEM_BUFF_TARGET_TYPE)uint.Parse(field.Value)) },
			"neb_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((BT_NEBTYPE)uint.Parse(field.Value)) },
			"drain_supplies" => field with { EnumValue = UtfDbTypeParserHelpers.FormatBoolean(uint.Parse(field.Value) != 0) },
			_ => field
		};
	}

	public static string[] ReadAscii32Array(ReadOnlySpan<byte> rawData, ref int offset, int count) {
		var values = new string[count];
		for (var index = 0; index < count; index++) values[index] = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref offset);
		return values;
	}

	public static BT_PLASMABOLT_SEGMENT[] ReadPlasmaBoltArray(ReadOnlySpan<byte> rawData, ref int offset, int count) {
		var values = new BT_PLASMABOLT_SEGMENT[count];
		for (var index = 0; index < count; index++) {
			values[index] = new BT_PLASMABOLT_SEGMENT {
				RollSpeed = UtfDbTypeParserHelpers.ParseBtVector(rawData, ref offset),
				BoltWidth = UtfDbTypeParserHelpers.ReadSingle(rawData, ref offset),
				BoltSpacing = UtfDbTypeParserHelpers.ReadSingle(rawData, ref offset),
				SegmentsX = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref offset),
				SegmentsY = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref offset),
				SegmentsZ = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref offset),
				Offset = UtfDbTypeParserHelpers.ParseBtVector(rawData, ref offset),
				BoltColor = UtfDbTypeParserHelpers.ParseColora(rawData, ref offset)
			};
		}
		return values;
	}
}

internal sealed class BT_AEBOLT_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_AEBOLT_DATA", "field", [
		UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"),
		new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("explosion_effect", ScalarKind.Ascii32),
		new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("max_velocity", ScalarKind.F4),
		new ScalarSpec("damage", ScalarKind.U4), new ScalarSpec("explosion_range", ScalarKind.F4),
		UtfDbTypeLayouts.ArmorData("armor_data")
	]);
	public string TypeName => "BT_AEBOLT_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate);
	private static BT_AEBOLT_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o = 0; var b = UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_AEBOLT_DATA { ObjClass = b.ObjClass, BEditDropable = b.BEditDropable, WpnClass = UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ExplosionEffect = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVelocity = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Damage = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), ExplosionRange = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), ArmorData = UtfDbTypeParserHelpers.ParseBtArmorData(rawData, ref o) }; }
}

internal sealed class BT_AEGIS_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_AEGIS_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("supply_per_sec", ScalarKind.F4), UtfDbTypeLayouts.SingleTechnode("needed_tech")]);
	public string TypeName => "BT_AEGIS_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate);
	private static BT_AEGIS_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o = 0; var b = UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_AEGIS_DATA { ObjClass = b.ObjClass, BEditDropable = b.BEditDropable, WpnClass = UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), SupplyPerSec = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), NeededTech = UtfDbTypeParserHelpers.ParseBtSingleTechnode(rawData, ref o) }; }
}

internal sealed class BT_ANIMOBJ_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_ANIMOBJ_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4), new ScalarSpec("anim_name", ScalarKind.Ascii32), new ScalarSpec("anim_size", ScalarKind.F4), new ScalarSpec("size_vel", ScalarKind.F4), new ScalarSpec("life_time", ScalarKind.F4), new ScalarSpec("flags_raw", ScalarKind.U1)]);
	public string TypeName => "BT_ANIMOBJ_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate);
	private static BT_ANIMOBJ_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o = 0; var b = UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_ANIMOBJ_DATA { ObjClass = b.ObjClass, BEditDropable = b.BEditDropable, FxClass = (EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), AnimName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AnimSize = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), SizeVel = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), LifeTime = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), FlagsRaw = rawData[o++] }; }
}

internal sealed class BT_ANTIMATTER_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_ANTIMATTER_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("field_class", ScalarKind.U4), new ScalarSpec("info_help_id", ScalarKind.U4), new ScalarSpec("texture_name", ScalarKind.Ascii32), new ScalarSpec("map_tex_name", ScalarKind.Ascii32), new ScalarSpec("software_tex_clear_name", ScalarKind.Ascii32), new ScalarSpec("software_tex_fog_name", ScalarKind.Ascii32), new ScalarSpec("height", ScalarKind.S4), new ScalarSpec("segment_width", ScalarKind.S4), new ScalarSpec("spacing", ScalarKind.S4), UtfDbTypeLayouts.MissionData("mission_data")]);
	public string TypeName => "BT_ANTIMATTER_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate);
	private static BT_ANTIMATTER_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o = 0; var b = UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_ANTIMATTER_DATA { ObjClass = b.ObjClass, BEditDropable = b.BEditDropable, FieldClass = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), InfoHelpId = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), TextureName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MapTexName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SoftwareTexClearName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SoftwareTexFogName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), Height = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), SegmentWidth = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), Spacing = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), MissionData = UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o) }; }
}

internal sealed class BT_ARC_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_ARC_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("damage", ScalarKind.U4), new ScalarSpec("jump_range", ScalarKind.F4), new ScalarSpec("feedback_range", ScalarKind.F4), new ScalarSpec("max_tendril_stages", ScalarKind.U4), new ScalarSpec("damage_drop", ScalarKind.F4), new ScalarSpec("max_targets", ScalarKind.U4), new ScalarSpec("period", ScalarKind.F4), new ScalarSpec("drain_supplies", ScalarKind.U1)]);
	public string TypeName => "BT_ARC_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate);
	private static BT_ARC_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o = 0; var b = UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_ARC_DATA { ObjClass = b.ObjClass, BEditDropable = b.BEditDropable, WpnClass = UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Damage = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), JumpRange = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), FeedbackRange = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MaxTendrilStages = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), DamageDrop = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MaxTargets = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Period = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), DrainSupplies = UtfDbTypeParserHelpers.ReadBooleanU1(rawData, ref o) }; }
}

internal sealed class BT_ASTEROIDFIELD_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_ASTEROIDFIELD_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseFieldData("base_field_data"), new RepeatSpec(new ScalarSpec("file_name", ScalarKind.Ascii32), 4), new ScalarSpec("dust_tex_name", ScalarKind.Ascii32), new ScalarSpec("mod_texture_name", ScalarKind.Ascii32), new ScalarSpec("map_tex_name", ScalarKind.Ascii32), new ScalarSpec("software_tex_clear_name", ScalarKind.Ascii32), new ScalarSpec("software_tex_fog_name", ScalarKind.Ascii32), UtfDbTypeLayouts.MissionData("mission_data"), UtfDbTypeLayouts.FieldAttributes("attributes"), new ScalarSpec("asteroids_per_square", ScalarKind.S4), new ScalarSpec("polyroids_per_square", ScalarKind.S4), new ScalarSpec("depth", ScalarKind.S4), new ScalarSpec("range", ScalarKind.S4), new ScalarSpec("max_drift_speed", ScalarKind.S4), new ScalarSpec("min_drift_speed", ScalarKind.S4), new ScalarSpec("stationary_percentage", ScalarKind.F4), new ScalarSpec("ambient_sfx", ScalarKind.U4), new ScalarSpec("mod_tex_speed_scale", ScalarKind.F4), new ScalarSpec("anim_size_min", ScalarKind.S4), new ScalarSpec("anim_size_max", ScalarKind.S4), new ScalarSpec("nuggets_per_square", ScalarKind.U4), new ScalarSpec("nugget_z_height", ScalarKind.F4), new RepeatSpec(new ScalarSpec("nugget_type", ScalarKind.Ascii32), 4), UtfDbTypeLayouts.Color("anim_color")]);
	public string TypeName => "BT_ASTEROIDFIELD_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate);
	private static BT_ASTEROIDFIELD_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o = 0; var b = UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_ASTEROIDFIELD_DATA { ObjClass = b.ObjClass, BEditDropable = b.BEditDropable, BaseFieldData = UtfDbTypeParserHelpers.ParseBaseFieldData(rawData, ref o), FileName = BTBatch2TypeParserSupport.ReadAscii32Array(rawData, ref o, 4), DustTexName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ModTextureName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MapTexName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SoftwareTexClearName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SoftwareTexFogName = UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MissionData = UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), Attributes = UtfDbTypeParserHelpers.ParseBtFieldAttributes(rawData, ref o), AsteroidsPerSquare = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), PolyroidsPerSquare = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), Depth = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), Range = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), MaxDriftSpeed = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), MinDriftSpeed = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), StationaryPercentage = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), AmbientSfx = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), ModTexSpeedScale = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), AnimSizeMin = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), AnimSizeMax = UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), NuggetsPerSquare = UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), NuggetZHeight = UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), NuggetType = BTBatch2TypeParserSupport.ReadAscii32Array(rawData, ref o, 4), AnimColor = UtfDbTypeParserHelpers.ParseBtColor(rawData, ref o) }; }
}

internal sealed class BT_DESTABILIZER_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_DESTABILIZER_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("explosion_effect", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("max_velocity", ScalarKind.F4), new ScalarSpec("explosion_range", ScalarKind.F4), new ScalarSpec("duration", ScalarKind.F4), UtfDbTypeLayouts.MissionData("mission_data")]); public string TypeName => "BT_DESTABILIZER_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_DESTABILIZER_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_DESTABILIZER_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ExplosionEffect=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVelocity=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), ExplosionRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Duration=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o) }; } }
internal sealed class BT_DUMBRECONPROBE_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_DUMBRECONPROBE_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("max_velocity", ScalarKind.F4), new ScalarSpec("duration", ScalarKind.F4), UtfDbTypeLayouts.MissionData("mission_data")]); public string TypeName => "BT_DUMBRECONPROBE_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_DUMBRECONPROBE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_DUMBRECONPROBE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVelocity=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Duration=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o) }; } }
internal sealed class BT_ENGINETRAILTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_ENGINETRAIL", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4), new ScalarSpec("width", ScalarKind.F4), new ScalarSpec("segments", ScalarKind.U4), new ScalarSpec("time_per_segment", ScalarKind.F4), new ScalarSpec("tapper_type", ScalarKind.U4), new ScalarSpec("tapper_mod", ScalarKind.F4), new ScalarSpec("hardpoint", ScalarKind.Ascii64), new ScalarSpec("texture", ScalarKind.Ascii32), UtfDbTypeLayouts.Colora("color_mod"), UtfDbTypeLayouts.Colora("engine_glow_color_mod"), new ScalarSpec("engine_glow_texture", ScalarKind.Ascii32), new ScalarSpec("engine_glow_width", ScalarKind.F4)]); public string TypeName => "BT_ENGINETRAIL"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_ENGINETRAIL ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_ENGINETRAIL { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FxClass=(EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Width=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Segments=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), TimePerSegment=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), TapperType=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), TapperMod=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Hardpoint=UtfDbTypeParserHelpers.ReadAscii64(rawData, ref o), Texture=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ColorMod=UtfDbTypeParserHelpers.ParseColora(rawData, ref o), EngineGlowColorMod=UtfDbTypeParserHelpers.ParseColora(rawData, ref o), EngineGlowTexture=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), EngineGlowWidth=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_EXTENSION_INFOTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_EXTENSION_INFO", "field", [new ScalarSpec("add_child_name", ScalarKind.Ascii32), new ScalarSpec("remove_child_name", ScalarKind.Ascii32), new ScalarSpec("archetype_name", ScalarKind.Ascii32)]); public string TypeName => "BT_EXTENSION_INFO"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue); private static BT_EXTENSION_INFO ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; return new BT_EXTENSION_INFO { AddChildName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), RemoveChildName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ArchetypeName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_GATTLINGBEAM_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_GATTLINGBEAM_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("damage", ScalarKind.U4), new ScalarSpec("lifetime", ScalarKind.F4), new ScalarSpec("max_sweep_dist", ScalarKind.F4), new ScalarSpec("beam_width", ScalarKind.F4), new ScalarSpec("contact_blast", ScalarKind.Ascii32)]); public string TypeName => "BT_GATTLINGBEAM_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_GATTLINGBEAM_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_GATTLINGBEAM_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Damage=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Lifetime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MaxSweepDist=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), BeamWidth=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), ContactBlast=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_MASS_DISRUPTOR_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_MASS_DISRUPTOR_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("contact_blast_type", ScalarKind.Ascii32), new ScalarSpec("warp_anim", ScalarKind.Ascii32), new ScalarSpec("anim_width", ScalarKind.U4), new ScalarSpec("bolt_speed", ScalarKind.F4), new ScalarSpec("damage_percent", ScalarKind.F4)]); public string TypeName => "BT_MASS_DISRUPTOR_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_MASS_DISRUPTOR_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_MASS_DISRUPTOR_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ContactBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), WarpAnim=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AnimWidth=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), BoltSpeed=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), DamagePercent=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_MESH_EXPLOSIONTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_MESH_EXPLOSION", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("secondary_blast_type", ScalarKind.Ascii32), new ScalarSpec("piece_blast_type", ScalarKind.Ascii32), new ScalarSpec("catastrophic_blast_type", ScalarKind.Ascii32), new ScalarSpec("ripple_blast_type", ScalarKind.Ascii32), new ScalarSpec("fire_trail", ScalarKind.Ascii32)]); public string TypeName => "BT_MESH_EXPLOSION"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_MESH_EXPLOSION ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_MESH_EXPLOSION { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, SecondaryBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), PieceBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), CatastrophicBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), RippleBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), FireTrail=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_MIMIC_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_MIMIC_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("supply_use", ScalarKind.F4), new ScalarSpec("shutoff", ScalarKind.F4), UtfDbTypeLayouts.SingleTechnode("tech_node")]); public string TypeName => "BT_MIMIC_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_MIMIC_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_MIMIC_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), SupplyUse=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Shutoff=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), TechNode=UtfDbTypeParserHelpers.ParseBtSingleTechnode(rawData, ref o) }; } }
internal sealed class BT_MINEFIELD_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_MINEFIELD_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("max_mine_number", ScalarKind.U4), new ScalarSpec("damage_per_hit", ScalarKind.U4), new ScalarSpec("supply_damage_per_hit", ScalarKind.U4), new ScalarSpec("hull_lost_per_hit", ScalarKind.U4), new ScalarSpec("mine_type", ScalarKind.U4), new ScalarSpec("reg_animation", ScalarKind.Ascii32), new ScalarSpec("blast_type", ScalarKind.Ascii32), new ScalarSpec("mine_width", ScalarKind.U4), new ScalarSpec("max_vertical_velocity", ScalarKind.S4), new ScalarSpec("max_horizontal_velocity", ScalarKind.S4), new ScalarSpec("mine_acceleration", ScalarKind.U4), new ScalarSpec("explosion_range", ScalarKind.F4), UtfDbTypeLayouts.ResourceCost("cost")]); public string TypeName => "BT_MINEFIELD_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_MINEFIELD_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_MINEFIELD_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), MaxMineNumber=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), DamagePerHit=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), SupplyDamagePerHit=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), HullLostPerHit=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MineType=(MINETYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), RegAnimation=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), BlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MineWidth=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVerticalVelocity=UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), MaxHorizontalVelocity=UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), MineAcceleration=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), ExplosionRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Cost=UtfDbTypeParserHelpers.ParseBtResourceCost(rawData, ref o) }; } }
internal sealed class BT_NEBULA_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_NEBULA_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseFieldData("base_field_data"), new ScalarSpec("cloud_effect", ScalarKind.Ascii32), new ScalarSpec("map_tex_name", ScalarKind.Ascii32), UtfDbTypeLayouts.MissionData("mission_data"), UtfDbTypeLayouts.FieldAttributes("attributes"), UtfDbTypeLayouts.AmbientNebulaLight("ambient"), new ScalarSpec("ambient_sfx", ScalarKind.U4), new ScalarSpec("neb_type", ScalarKind.U4), new ScalarSpec("nuggets_per_square", ScalarKind.U4), new ScalarSpec("nugget_z_height", ScalarKind.F4), new RepeatSpec(new ScalarSpec("nugget_type", ScalarKind.Ascii32), 4)]); public string TypeName => "BT_NEBULA_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_NEBULA_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_NEBULA_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, BaseFieldData=UtfDbTypeParserHelpers.ParseBaseFieldData(rawData, ref o), CloudEffect=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MapTexName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), Attributes=UtfDbTypeParserHelpers.ParseBtFieldAttributes(rawData, ref o), Ambient=UtfDbTypeParserHelpers.ParseBtAmbientNebulaLight(rawData, ref o), AmbientSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), NebType=(BT_NEBTYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), NuggetsPerSquare=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), NuggetZHeight=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), NuggetType=BTBatch2TypeParserSupport.ReadAscii32Array(rawData, ref o, 4) }; } }
internal sealed class BT_NOVA_EXPLOSIONTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_NOVA_EXPLOSION", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4), new ScalarSpec("inter_ring_time", ScalarKind.F4), new ScalarSpec("ring_time", ScalarKind.F4), new ScalarSpec("range", ScalarKind.F4), new ScalarSpec("duration", ScalarKind.F4)]); public string TypeName => "BT_NOVA_EXPLOSION"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_NOVA_EXPLOSION ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_NOVA_EXPLOSION { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FxClass=(EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), InterRingTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), RingTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Range=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Duration=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_PARTICLE_CIRCLETypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PARTICLE_CIRCLE", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4), UtfDbTypeLayouts.Color("color")]); public string TypeName => "BT_PARTICLE_CIRCLE"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_PARTICLE_CIRCLE ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_PARTICLE_CIRCLE { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FxClass=(EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Color=UtfDbTypeParserHelpers.ParseBtColor(rawData, ref o) }; } }
internal sealed class BT_PARTICLE_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PARTICLE_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4), new ScalarSpec("file_name", ScalarKind.Ascii32)]); public string TypeName => "BT_PARTICLE_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_PARTICLE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_PARTICLE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FxClass=(EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_PKBOLT_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PKBOLT_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("explosion_effect", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("max_velocity", ScalarKind.F4), new ScalarSpec("new_planet_type", ScalarKind.Ascii32), new ScalarSpec("change_time", ScalarKind.F4), new ScalarSpec("engine_trail_type", ScalarKind.Ascii32)]); public string TypeName => "BT_PKBOLT_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_PKBOLT_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_PKBOLT_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ExplosionEffect=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVelocity=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), NewPlanetType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ChangeTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), EngineTrailType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_PLASMABOLT_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PLASMABOLT_DATA", "field", [UtfDbTypeLayouts.ProjectileDataBase("base"), new ScalarSpec("texture_name", ScalarKind.Ascii32), new ScalarSpec("anim_name", ScalarKind.Ascii32), new ScalarSpec("num_bolts", ScalarKind.F4), new RepeatSpec(new GroupSpec("bolts", [UtfDbTypeLayouts.BtVector("roll_speed"), new ScalarSpec("bolt_width", ScalarKind.F4), new ScalarSpec("bolt_spacing", ScalarKind.F4), new ScalarSpec("segments_x", ScalarKind.U4), new ScalarSpec("segments_y", ScalarKind.U4), new ScalarSpec("segments_z", ScalarKind.U4), UtfDbTypeLayouts.BtVector("offset"), UtfDbTypeLayouts.Colora("bolt_color")]), 4)]); public string TypeName => "BT_PLASMABOLT_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_PLASMABOLT_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bp=UtfDbTypeParserHelpers.ParseBtProjectileDataBase(rawData, ref o); return new BT_PLASMABOLT_DATA { ObjClass=bp.Base.ObjClass, BEditDropable=bp.Base.BEditDropable, BaseProjectile=bp, TextureName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AnimName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), NumBolts=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Bolts=BTBatch2TypeParserSupport.ReadPlasmaBoltArray(rawData, ref o, 4) }; } }
internal sealed class BT_REPELLENTCLOUD_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_REPELLENTCLOUD_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("explosion_effect", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("duration", ScalarKind.F4), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("damage_per_sec", ScalarKind.U4), new ScalarSpec("center_range", ScalarKind.F4)]); public string TypeName => "BT_REPELLENTCLOUD_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_REPELLENTCLOUD_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_REPELLENTCLOUD_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), ExplosionEffect=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Duration=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), DamagePerSec=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), CenterRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_REPULSOR_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_REPULSOR_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("hardpoint", ScalarKind.Ascii64), new ScalarSpec("contact_blast_type", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("push_time", ScalarKind.F4), new ScalarSpec("minimum_mass", ScalarKind.F4), new ScalarSpec("base_push_power", ScalarKind.F4), new ScalarSpec("push_per_mass", ScalarKind.F4), UtfDbTypeLayouts.SingleTechnode("needed_tech")]); public string TypeName => "BT_REPULSOR_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_REPULSOR_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_REPULSOR_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), Hardpoint=UtfDbTypeParserHelpers.ReadAscii64(rawData, ref o), ContactBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), PushTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MinimumMass=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), BasePushPower=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), PushPerMass=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), NeededTech=UtfDbTypeParserHelpers.ParseBtSingleTechnode(rawData, ref o) }; } }
internal sealed class BT_REPULSORWAVE_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_REPULSORWAVE_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("duration", ScalarKind.F4), new ScalarSpec("range", ScalarKind.F4), new ScalarSpec("ring_time", ScalarKind.F4), new ScalarSpec("inter_ring_time", ScalarKind.F4), UtfDbTypeLayouts.MissionData("mission_data")]); public string TypeName => "BT_REPULSORWAVE_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_REPULSORWAVE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_REPULSORWAVE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Duration=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Range=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), RingTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), InterRingTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o) }; } }
internal sealed class BT_SPACEWAVE_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_SPACEWAVE_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class")]); public string TypeName => "BT_SPACEWAVE_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_SPACEWAVE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_SPACEWAVE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o) }; } }
internal sealed class BT_STASISBOLT_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_STASISBOLT_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("explosion_effect", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("max_velocity", ScalarKind.F4), new ScalarSpec("explosion_range", ScalarKind.F4), new ScalarSpec("duration", ScalarKind.F4), UtfDbTypeLayouts.MissionData("mission_data")]); public string TypeName => "BT_STASISBOLT_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_STASISBOLT_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_STASISBOLT_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ExplosionEffect=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVelocity=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), ExplosionRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Duration=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o) }; } }
internal sealed class BT_SYSTEM_BUFF_LAUNCHERTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_SYSTEM_BUFF_LAUNCHER", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseLauncher("type"), new ScalarSpec("buff_type", ScalarKind.U4), new ScalarSpec("target_type", ScalarKind.U4)]); public string TypeName => "BT_SYSTEM_BUFF_LAUNCHER"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_SYSTEM_BUFF_LAUNCHER ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_SYSTEM_BUFF_LAUNCHER { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, Type=UtfDbTypeParserHelpers.ParseBaseLauncher(rawData, ref o), BuffType=(BT_SYSTEM_BUFF_TYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), TargetType=(BT_SYSTEM_BUFF_TARGET_TYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) }; } }
internal sealed class BT_TALORIAN_EFFECTTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TALORIAN_EFFECT", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4)]); public string TypeName => "BT_TALORIAN_EFFECT"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_TALORIAN_EFFECT ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_TALORIAN_EFFECT { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FxClass=(EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) }; } }
internal sealed class BT_TEMPHQ_LAUNCHERTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TEMPHQ_LAUNCHER", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseLauncher("type"), new ScalarSpec("charge_regen_rate", ScalarKind.F4), new ScalarSpec("charge_use_rate", ScalarKind.F4), new ScalarSpec("max_charge", ScalarKind.F4)]); public string TypeName => "BT_TEMPHQ_LAUNCHER"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_TEMPHQ_LAUNCHER ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_TEMPHQ_LAUNCHER { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, Type=UtfDbTypeParserHelpers.ParseBaseLauncher(rawData, ref o), ChargeRegenRate=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), ChargeUseRate=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MaxCharge=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_TRAIL_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TRAIL_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("anim", ScalarKind.Ascii32)]); public string TypeName => "BT_TRAIL_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch2TypeParserSupport.Annotate); private static BT_TRAIL_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_TRAIL_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, Anim=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
