using System.Xml.Linq;
using ConquestFrontierWarsRay.Data.Models;
using ConquestFrontierWarsRay.Data.Models.BT;
using ConquestFrontierWarsRay.Data.UtfDb.Models;

namespace ConquestFrontierWarsRay.Data.UtfDb.Types;

internal static class BTBatch3TypeParserSupport {
	public static UtfDbField Annotate(UtfDbField field) {
		return field.Label switch {
			"base.obj_class" or "base_data.base.obj_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((OBJCLASS)uint.Parse(field.Value)) },
			"base.b_edit_dropable" or "base_data.base.b_edit_dropable" => field with { EnumValue = UtfDbTypeParserHelpers.FormatBoolean(uint.Parse(field.Value) != 0) },
			"type.type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((LAUNCHCLASS)uint.Parse(field.Value)) },
			"wpn_class.wpn_class" or "base_projectile.wpn_class.wpn_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((WPNCLASS)uint.Parse(field.Value)) },
			"base_data.type" or "spaceship_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((SPACESHIPCLASS)uint.Parse(field.Value)) },
			"fx_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((EFFECTCLASS)uint.Parse(field.Value)) },
			"bo_class" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((BUILDOBJCLASS)uint.Parse(field.Value)) },
			"res_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((M_RESOURCE_TYPE)uint.Parse(field.Value)) },
			"nugget_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((M_NUGGET_TYPE)uint.Parse(field.Value)) },
			"planet_type" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((PLANET_TYPE)uint.Parse(field.Value)) },
			"launch_sfx" or "enter1" or "enter2" or "arrive1" or "arrive2" or "ambience" or "docking_sound" or "nugget_sound" or "kamikaze_yell" or "fighterwhoosh" or "fighter_launch" => field with { EnumValue = UtfDbTypeParserHelpers.FormatEnum((SFX_ID)uint.Parse(field.Value)) },
			"no_line_of_sight" or "start_enabled" or "oriented" or "z_render" => field with { EnumValue = UtfDbTypeParserHelpers.FormatBoolean(uint.Parse(field.Value) != 0) },
			_ => BTBatch2TypeParserSupport.Annotate(field)
		};
	}

	public static BT_BILLBOARD_MESH[] ReadBillboardMeshArray(ReadOnlySpan<byte> rawData, ref int offset, int count) {
		var values = new BT_BILLBOARD_MESH[count];
		for (var i = 0; i < count; i++) values[i] = UtfDbTypeParserHelpers.ParseBtBillboardMesh(rawData, ref offset);
		return values;
	}

	public static BT_PLAYER_RACE[] ReadPlayerRaceArray(ReadOnlySpan<byte> rawData, ref int offset, int count) {
		var values = new BT_PLAYER_RACE[count];
		for (var i = 0; i < count; i++) values[i] = UtfDbTypeParserHelpers.ParseBtPlayerRace(rawData, ref offset);
		return values;
	}

	public static float[] ReadSingleArray(ReadOnlySpan<byte> rawData, ref int offset, int count) {
		var values = new float[count];
		for (var i = 0; i < count; i++) values[i] = UtfDbTypeParserHelpers.ReadSingle(rawData, ref offset);
		return values;
	}
}

internal sealed class BT_BLACKHOLE_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_BLACKHOLE_DATA", "field", [UtfDbTypeLayouts.BasicData(), new RepeatSpec(UtfDbTypeLayouts.BillboardMesh("billboard_mesh"), 3), new ScalarSpec("ring_object_name", ScalarKind.Ascii32), new ScalarSpec("sys_map_icon", ScalarKind.Ascii32), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("damage", ScalarKind.U4)]);
	public string TypeName => "BT_BLACKHOLE_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_BLACKHOLE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_BLACKHOLE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, BillboardMesh=BTBatch3TypeParserSupport.ReadBillboardMeshArray(rawData, ref o, 3), RingObjectName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SysMapIcon=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), Damage=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) }; }
}

internal sealed class BT_BUILDERSHIP_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_BUILDERSHIP_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("spaceship_class", ScalarKind.U4), new ScalarSpec("file_name", ScalarKind.Ascii32), UtfDbTypeLayouts.DynamicsDataJr("dynamics_data"), new ScalarSpec("work_animation", ScalarKind.Ascii32), new ScalarSpec("spark_anim", ScalarKind.Ascii32), new ScalarSpec("spark_hardpoint", ScalarKind.Ascii32), new ScalarSpec("explosion_type", ScalarKind.Ascii32), new ScalarSpec("spark_width", ScalarKind.F4), new ScalarSpec("spark_delay", ScalarKind.F4)]);
	public string TypeName => "BT_BUILDERSHIP_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_BUILDERSHIP_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_BUILDERSHIP_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, SpaceshipClass=(SPACESHIPCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), DynamicsData=UtfDbTypeParserHelpers.ParseBtDynamicsDataJr(rawData, ref o), WorkAnimation=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SparkAnim=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SparkHardpoint=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ExplosionType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SparkWidth=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), SparkDelay=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; }
}

internal sealed class BT_FIGHTER_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_FIGHTER_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("file_name", ScalarKind.Ascii32), UtfDbTypeLayouts.DynamicsData("dynamics_data"), UtfDbTypeLayouts.ArmorData("armor_data"), new ScalarSpec("explosion_type", ScalarKind.Ascii32), new ScalarSpec("weapon_type", ScalarKind.Ascii32), new ScalarSpec("engine_trail_type", ScalarKind.Ascii32), new ScalarSpec("sensor_radius", ScalarKind.U2), new ScalarSpec("cloaked_sensor_radius", ScalarKind.U2), new ScalarSpec("patrol_radius", ScalarKind.F4), new ScalarSpec("patrol_altitude", ScalarKind.F4), new ScalarSpec("attack_range", ScalarKind.F4), new ScalarSpec("dodge", ScalarKind.F4), new ScalarSpec("hull_points_max", ScalarKind.U4), new ScalarSpec("max_supplies", ScalarKind.U4), new ScalarSpec("refire_period", ScalarKind.F4), new ScalarSpec("patrol_period", ScalarKind.F4), new ScalarSpec("kamikaze_damage", ScalarKind.U4), new ScalarSpec("kamikaze_yell", ScalarKind.U4), new ScalarSpec("fighterwhoosh", ScalarKind.U4), new ScalarSpec("fighter_launch", ScalarKind.U4)]);
	public string TypeName => "BT_FIGHTER_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_FIGHTER_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_FIGHTER_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), DynamicsData=UtfDbTypeParserHelpers.ParseBtDynamicsData(rawData, ref o), ArmorData=UtfDbTypeParserHelpers.ParseBtArmorData(rawData, ref o), ExplosionType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), WeaponType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), EngineTrailType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SensorRadius=UtfDbTypeParserHelpers.ReadUInt16(rawData, ref o), CloakedSensorRadius=UtfDbTypeParserHelpers.ReadUInt16(rawData, ref o), PatrolRadius=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), PatrolAltitude=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), AttackRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Dodge=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), HullPointsMax=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxSupplies=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), RefirePeriod=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), PatrolPeriod=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), KamikazeDamage=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), KamikazeYell=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), FighterWhoosh=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), FighterLaunch=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) }; }
}

internal sealed class BT_GUNBOAT_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_GUNBOAT_DATA", "field", [UtfDbTypeLayouts.BaseSpaceshipData("base_data"), new ScalarSpec("outer_weapon_range", ScalarKind.F4), new ScalarSpec("optimal_facing_angle", ScalarKind.F4), new ScalarSpec("no_line_of_sight", ScalarKind.U1), new RepeatSpec(new ScalarSpec("launcher_type", ScalarKind.Ascii32), 5), new PaddingSpec("padding", 3)]);
	public string TypeName => "BT_GUNBOAT_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_GUNBOAT_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bd=UtfDbTypeParserHelpers.ParseBtBaseSpaceshipData(rawData, ref o); var v=new BT_GUNBOAT_DATA { ObjClass=bd.Base.ObjClass, BEditDropable=bd.Base.BEditDropable, BaseData=bd, OuterWeaponRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), OptimalFacingAngle=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), NoLineOfSight=UtfDbTypeParserHelpers.ReadBooleanU1(rawData, ref o), LauncherType=BTBatch2TypeParserSupport.ReadAscii32Array(rawData, ref o, 5) }; o+=3; return v; }
}

internal sealed class BT_HARVESTSHIP_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_HARVESTSHIP_DATA", "field", [UtfDbTypeLayouts.BaseSpaceshipData("base_data"), new ScalarSpec("loading_rate", ScalarKind.U4), new GroupSpec("dock_timing", [new ScalarSpec("unload_rate", ScalarKind.F4), new ScalarSpec("off_dist", ScalarKind.F4), new ScalarSpec("docking_sound", ScalarKind.U4)]), new GroupSpec("nugget_timing", [new ScalarSpec("nugget_time", ScalarKind.F4), new ScalarSpec("off_dist", ScalarKind.F4), new ScalarSpec("mine_per_second", ScalarKind.F4), new ScalarSpec("hardpoint_name", ScalarKind.Ascii32), new ScalarSpec("nugget_sound", ScalarKind.U4)]), new ScalarSpec("gas_tank_mesh", ScalarKind.Ascii32), new ScalarSpec("metal_tank_mesh", ScalarKind.Ascii32)]);
	public string TypeName => "BT_HARVESTSHIP_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_HARVESTSHIP_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bd=UtfDbTypeParserHelpers.ParseBtBaseSpaceshipData(rawData, ref o); return new BT_HARVESTSHIP_DATA { ObjClass=bd.Base.ObjClass, BEditDropable=bd.Base.BEditDropable, BaseData=bd, LoadingRate=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), DockTiming=UtfDbTypeParserHelpers.ParseBtDockTiming(rawData, ref o), NuggetTiming=UtfDbTypeParserHelpers.ParseBtNuggetTiming(rawData, ref o), GasTankMesh=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MetalTankMesh=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; }
}

internal sealed class BT_JUMPGATE_DATATypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_JUMPGATE_DATA", "field", [UtfDbTypeLayouts.BasicData(), new RepeatSpec(UtfDbTypeLayouts.BillboardMesh("billboard_mesh"), 3), new ScalarSpec("enter1", ScalarKind.U4), new ScalarSpec("enter2", ScalarKind.U4), new ScalarSpec("arrive1", ScalarKind.U4), new ScalarSpec("arrive2", ScalarKind.U4), new ScalarSpec("ambience", ScalarKind.U4), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("min_hold_time", ScalarKind.F4), new ScalarSpec("min_stagger_time", ScalarKind.F4)]);
	public string TypeName => "BT_JUMPGATE_DATA";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_JUMPGATE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_JUMPGATE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, BillboardMesh=BTBatch3TypeParserSupport.ReadBillboardMeshArray(rawData, ref o, 3), Enter1=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Enter2=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Arrive1=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Arrive2=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Ambience=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), MinHoldTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MinStaggerTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; }
}

internal sealed class BT_LISTEN_ARTIFACTTypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_LISTEN_ARTIFACT", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("ship_name", ScalarKind.Ascii32), new ScalarSpec("success_chance", ScalarKind.F4), UtfDbTypeLayouts.ArtifactButtonInfo("button_info")]);
	public string TypeName => "BT_LISTEN_ARTIFACT";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_LISTEN_ARTIFACT ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_LISTEN_ARTIFACT { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), ShipName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SuccessChance=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), ButtonInfo=UtfDbTypeParserHelpers.ParseBtArtifactButtonInfo(rawData, ref o) }; }
}

internal sealed class BT_MANTIS_BUILDTypeParser : IUtfDbTypeParser {
	private static readonly FixedLayoutTypeParser FieldParser = new("BT_MANTIS_BUILD", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("bo_class", ScalarKind.U4), new ScalarSpec("cocoon_texture_name", ScalarKind.Ascii32)]);
	public string TypeName => "BT_MANTIS_BUILD";
	public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate);
	private static BT_MANTIS_BUILD ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_MANTIS_BUILD { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, BoClass=(BUILDOBJCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), CocoonTextureName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; }
}

internal sealed class BT_MOVIE_CAMERA_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_MOVIE_CAMERA_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("file_name", ScalarKind.Ascii32), UtfDbTypeLayouts.MissionData("mission_data")]); public string TypeName => "BT_MOVIE_CAMERA_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_MOVIE_CAMERA_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_MOVIE_CAMERA_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o) }; } }
internal sealed class BT_MINELAYER_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_MINELAYER_DATA", "field", [UtfDbTypeLayouts.BaseSpaceshipData("base_data"), new ScalarSpec("drop_anim", ScalarKind.Ascii32), new ScalarSpec("mine_field_type", ScalarKind.Ascii32), new ScalarSpec("mine_release_hardpoint", ScalarKind.Ascii32), new ScalarSpec("field_supply_cost_per_mine", ScalarKind.U1), new PaddingSpec("padding", 3), new ScalarSpec("field_completion_time", ScalarKind.U4), new ScalarSpec("mine_release_velocity", ScalarKind.U4), new ScalarSpec("drop_anim_delay", ScalarKind.F4)]); public string TypeName => "BT_MINELAYER_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_MINELAYER_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bd=UtfDbTypeParserHelpers.ParseBtBaseSpaceshipData(rawData, ref o); var value = new BT_MINELAYER_DATA { ObjClass=bd.Base.ObjClass, BEditDropable=bd.Base.BEditDropable, BaseData=bd, DropAnim=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MineFieldType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MineReleaseHardpoint=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), FieldSupplyCostPerMine=rawData[o++] }; o += 3; value.FieldCompletionTime=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o); value.MineReleaseVelocity=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o); value.DropAnimDelay=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o); return value; } }
internal sealed class BT_NUGGET_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_NUGGET_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("nugget_anim_2d", ScalarKind.Ascii32), new ScalarSpec("nugget_mesh", ScalarKind.Ascii32), new ScalarSpec("anim_size_small_max", ScalarKind.S4), new ScalarSpec("anim_size_max", ScalarKind.S4), new ScalarSpec("anim_size_min", ScalarKind.S4), UtfDbTypeLayouts.ComplexColor("color"), new ScalarSpec("oriented", ScalarKind.U1), new ScalarSpec("z_render", ScalarKind.U1), new PaddingSpec("padding", 2), new ScalarSpec("res_type", ScalarKind.U4), new ScalarSpec("nugget_type", ScalarKind.U4), new ScalarSpec("max_supplies", ScalarKind.U4)]); public string TypeName => "BT_NUGGET_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_NUGGET_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); var v = new BT_NUGGET_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, NuggetAnim2D=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), NuggetMesh=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AnimSizeSmallMax=UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), AnimSizeMax=UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), AnimSizeMin=UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), Color=UtfDbTypeParserHelpers.ParseBtComplexColor(rawData, ref o), Oriented=UtfDbTypeParserHelpers.ReadBooleanU1(rawData, ref o), ZRender=UtfDbTypeParserHelpers.ReadBooleanU1(rawData, ref o) }; o+=2; v.ResType=(M_RESOURCE_TYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o); v.NuggetType=(M_NUGGET_TYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o); v.MaxSupplies=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o); return v; } }
internal sealed class BT_OBJECT_GENERATORTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_OBJECT_GENERATOR", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("file_name", ScalarKind.Ascii32), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("mean", ScalarKind.F4), new ScalarSpec("min_diff", ScalarKind.F4), new ScalarSpec("generate_type", ScalarKind.Ascii32), new ScalarSpec("start_enabled", ScalarKind.U4)]); public string TypeName => "BT_OBJECT_GENERATOR"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_OBJECT_GENERATOR ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_OBJECT_GENERATOR { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), Mean=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), MinDiff=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), GenerateType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), StartEnabled=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) != 0 }; } }
internal sealed class BT_PLANET_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PLANET_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("file_mame", ScalarKind.Ascii32), new ScalarSpec("ambient_animation", ScalarKind.Ascii32), new ScalarSpec("sys_map_icon", ScalarKind.Ascii32), new ScalarSpec("ambient_effect", ScalarKind.Ascii32), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("max_metal", ScalarKind.U2), new ScalarSpec("max_gas", ScalarKind.U2), new ScalarSpec("max_crew", ScalarKind.U2), new PaddingSpec("padding", 2), new ScalarSpec("metal_regen", ScalarKind.F4), new ScalarSpec("gas_regen", ScalarKind.F4), new ScalarSpec("crew_regen", ScalarKind.F4), new ScalarSpec("planet_type", ScalarKind.U4), new ScalarSpec("terra_particle", ScalarKind.Ascii32), UtfDbTypeLayouts.Color("tera_color"), new ScalarSpec("tera_explosions", ScalarKind.Ascii32), new ScalarSpec("padding1", ScalarKind.U1), new GroupSpec("halo", [UtfDbTypeLayouts.Color("color"), new ScalarSpec("padding", ScalarKind.U1), new ScalarSpec("size_inner", ScalarKind.F4), new ScalarSpec("size_outer", ScalarKind.F4)]), new ScalarSpec("flags", ScalarKind.U1)]); public string TypeName => "BT_PLANET_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_PLANET_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); var v = new BT_PLANET_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FileMame=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AmbientAnimation=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), SysMapIcon=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AmbientEffect=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), MaxMetal=UtfDbTypeParserHelpers.ReadUInt16(rawData, ref o), MaxGas=UtfDbTypeParserHelpers.ReadUInt16(rawData, ref o), MaxCrew=UtfDbTypeParserHelpers.ReadUInt16(rawData, ref o) }; o+=2; v.MetalRegen=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o); v.GasRegen=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o); v.CrewRegen=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o); v.PlanetType=(PLANET_TYPE)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o); v.TerraParticle=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o); v.TeraColor=UtfDbTypeParserHelpers.ParseBtColor(rawData, ref o); v.TeraExplosions=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o); o+=1; v.Halo=UtfDbTypeParserHelpers.ParseBtPlanetHalo(rawData, ref o); v.Flags=rawData[o++]; return v; } }
internal sealed class BT_PLAYERBOMB_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PLAYERBOMB_DATA", "field", [UtfDbTypeLayouts.BasicData(), new RepeatSpec(new GroupSpec("race", [new RepeatSpec(new GroupSpec("min_bomb_type", [new ScalarSpec("archetype_name", ScalarKind.Ascii32)]), 4), new RepeatSpec(new GroupSpec("bomb_type", [new ScalarSpec("archetype_name", ScalarKind.Ascii32)]), 4), new RepeatSpec(new GroupSpec("large_bomb_type", [new ScalarSpec("archetype_name", ScalarKind.Ascii32)]), 8)]), 4), new ScalarSpec("player_bomb_anim_2d", ScalarKind.Ascii32), new ScalarSpec("anim_size", ScalarKind.U4), UtfDbTypeLayouts.MissionData("mission_data"), new ScalarSpec("filename", ScalarKind.Ascii32)]); public string TypeName => "BT_PLAYERBOMB_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_PLAYERBOMB_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_PLAYERBOMB_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, Race=BTBatch3TypeParserSupport.ReadPlayerRaceArray(rawData, ref o, 4), PlayerBombAnim2D=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), AnimSize=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MissionData=UtfDbTypeParserHelpers.ParseBtMissionData(rawData, ref o), Filename=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_PROJECTILE_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_PROJECTILE_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("file_name", ScalarKind.Ascii32), new ScalarSpec("launch_sfx", ScalarKind.U4), new ScalarSpec("damage", ScalarKind.U4), new ScalarSpec("max_velocity", ScalarKind.F4), new ScalarSpec("blast_type", ScalarKind.Ascii32), new ScalarSpec("engine_trail_type", ScalarKind.Ascii32)]); public string TypeName => "BT_PROJECTILE_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_PROJECTILE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_PROJECTILE_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), FileName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), Damage=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), MaxVelocity=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), BlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), EngineTrailType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_RECONPROBE_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_RECONPROBE_DATA", "field", [UtfDbTypeLayouts.BaseSpaceshipData("base_data"), new ScalarSpec("life_time", ScalarKind.F4), new ScalarSpec("blast_type", ScalarKind.Ascii32)]); public string TypeName => "BT_RECONPROBE_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_RECONPROBE_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bd=UtfDbTypeParserHelpers.ParseBtBaseSpaceshipData(rawData, ref o); return new BT_RECONPROBE_DATA { ObjClass=bd.Base.ObjClass, BEditDropable=bd.Base.BEditDropable, BaseData=bd, LifeTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), BlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_STREAK_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_STREAK_DATA", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("fx_class", ScalarKind.U4), new ScalarSpec("anim_name", ScalarKind.Ascii32), new ScalarSpec("num_lines", ScalarKind.U4), new ScalarSpec("line_time", ScalarKind.F4)]); public string TypeName => "BT_STREAK_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_STREAK_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_STREAK_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, FxClass=(EFFECTCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), AnimName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), NumLines=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o), LineTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_SUPPLYSHIP_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_SUPPLYSHIP_DATA", "field", [UtfDbTypeLayouts.BaseSpaceshipData("base_data"), new ScalarSpec("supplies_per_second", ScalarKind.F4), new ScalarSpec("supply_range", ScalarKind.F4)]); public string TypeName => "BT_SUPPLYSHIP_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_SUPPLYSHIP_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bd=UtfDbTypeParserHelpers.ParseBtBaseSpaceshipData(rawData, ref o); return new BT_SUPPLYSHIP_DATA { ObjClass=bd.Base.ObjClass, BEditDropable=bd.Base.BEditDropable, BaseData=bd, SuppliesPerSecond=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), SupplyRange=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_SWAPPER_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_SWAPPER_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("launch_sfx", ScalarKind.U4)]); public string TypeName => "BT_SWAPPER_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_SWAPPER_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_SWAPPER_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), LaunchSfx=UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) }; } }
internal sealed class BT_SYNTHESIS_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_SYNTHESIS_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), UtfDbTypeLayouts.SingleTechnode("tech_node"), new ScalarSpec("anim_name", ScalarKind.Ascii32)]); public string TypeName => "BT_SYNTHESIS_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_SYNTHESIS_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_SYNTHESIS_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), TechNode=UtfDbTypeParserHelpers.ParseBtSingleTechnode(rawData, ref o), AnimName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_TALORIAN_LAUNCHERTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TALORIAN_LAUNCHER", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseLauncher("type")]); public string TypeName => "BT_TALORIAN_LAUNCHER"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_TALORIAN_LAUNCHER ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_TALORIAN_LAUNCHER { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, Type=UtfDbTypeParserHelpers.ParseBaseLauncher(rawData, ref o) }; } }
internal sealed class BT_TERRAFORM_ARTIFACTTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TERRAFORM_ARTIFACT", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("ship_name", ScalarKind.Ascii32), UtfDbTypeLayouts.ArtifactButtonInfo("button_info"), new ScalarSpec("target_planet_type", ScalarKind.Ascii32), new ScalarSpec("change_time", ScalarKind.F4)]); public string TypeName => "BT_TERRAFORM_ARTIFACT"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_TERRAFORM_ARTIFACT ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_TERRAFORM_ARTIFACT { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), ShipName=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ButtonInfo=UtfDbTypeParserHelpers.ParseBtArtifactButtonInfo(rawData, ref o), TargetPlanetType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), ChangeTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o) }; } }
internal sealed class BT_TERRAN_BUILDTypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TERRAN_BUILD", "field", [UtfDbTypeLayouts.BasicData(), new ScalarSpec("bo_class", ScalarKind.U4)]); public string TypeName => "BT_TERRAN_BUILD"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_TERRAN_BUILD ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_TERRAN_BUILD { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, BoClass=(BUILDOBJCLASS)UtfDbTypeParserHelpers.ReadUInt32(rawData, ref o) }; } }
internal sealed class BT_TORPEDO_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_TORPEDO_DATA", "field", [UtfDbTypeLayouts.BaseSpaceshipData("base_data"), new ScalarSpec("life_time", ScalarKind.F4), new ScalarSpec("damage", ScalarKind.S4), new ScalarSpec("blast_type", ScalarKind.Ascii32)]); public string TypeName => "BT_TORPEDO_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_TORPEDO_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var bd=UtfDbTypeParserHelpers.ParseBtBaseSpaceshipData(rawData, ref o); return new BT_TORPEDO_DATA { ObjClass=bd.Base.ObjClass, BEditDropable=bd.Base.BEditDropable, BaseData=bd, LifeTime=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), Damage=UtfDbTypeParserHelpers.ReadInt32(rawData, ref o), BlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o) }; } }
internal sealed class BT_ZEALOT_DATATypeParser : IUtfDbTypeParser { private static readonly FixedLayoutTypeParser FieldParser = new("BT_ZEALOT_DATA", "field", [UtfDbTypeLayouts.BasicData(), UtfDbTypeLayouts.BaseWeaponData("wpn_class"), new ScalarSpec("kamikaze_speed", ScalarKind.F4), new RepeatSpec(new ScalarSpec("damage_amount", ScalarKind.F4), 3), new ScalarSpec("impact_blast_type", ScalarKind.Ascii32), UtfDbTypeLayouts.SingleTechnode("needed_tech")]); public string TypeName => "BT_ZEALOT_DATA"; public UtfDbEntryDetails Parse(string databaseName, string fileName, ReadOnlySpan<byte> rawData, XDocument? xmlDocument) => UtfDbTypeParserHelpers.ParseTyped(databaseName, fileName, rawData, xmlDocument, FieldParser, ParseTypedValue, BTBatch3TypeParserSupport.Annotate); private static BT_ZEALOT_DATA ParseTypedValue(ReadOnlySpan<byte> rawData) { var o=0; var b=UtfDbTypeParserHelpers.ParseBasicData(rawData, ref o); return new BT_ZEALOT_DATA { ObjClass=b.ObjClass, BEditDropable=b.BEditDropable, WpnClass=UtfDbTypeParserHelpers.ParseBaseWeaponData(rawData, ref o), KamikazeSpeed=UtfDbTypeParserHelpers.ReadSingle(rawData, ref o), DamageAmount=BTBatch3TypeParserSupport.ReadSingleArray(rawData, ref o, 3), ImpactBlastType=UtfDbTypeParserHelpers.ReadAscii32(rawData, ref o), NeededTech=UtfDbTypeParserHelpers.ParseBtSingleTechnode(rawData, ref o) }; } }
