using ConquestFrontierWarsRay.Data.UtfDb.Types;

namespace ConquestFrontierWarsRay.Data.UtfDb;

public static class UtfDbSupportedTypes {
	public static readonly IReadOnlyDictionary<string, IUtfDbTypeParser> Parsers =
		new Dictionary<string, IUtfDbTypeParser>(StringComparer.OrdinalIgnoreCase) {
			["MT_STRINGPACK"] = new RepeatedAscii32TypeParser("MT_STRINGPACK", "element", "element"),
			["MT_UNITSPEECH"] = new FixedLayoutTypeParser("MT_UNITSPEECH", "field",
				UtfDbTypeLayouts.FixedAscii32Layout("field", 22)),
			["BT_GROUP"] = new BT_GROUPTypeParser(),
			["BT_LIGHT"] = new BT_LIGHTTypeParser(),
			["BT_AIR_DEFENSE"] = new BT_AIR_DEFENSETypeParser(),
			["BT_ARTIFACT_LAUNCHER"] = new BT_ARTIFACT_LAUNCHERTypeParser(),
			["BT_ARTILERY_LAUNCHER"] = new BT_ARTILERY_LAUNCHERTypeParser(),
			["BT_BARRAGE_LAUNCHER"] = new BT_BARRAGE_LAUNCHERTypeParser(),
			["BT_BEAM_DATA"] = new BT_BEAM_DATATypeParser(),
			["BT_BLAST"] = new BT_BLASTTypeParser(),
			["BT_BUFF_ARTIFACT"] = new BT_BUFF_ARTIFACTTypeParser(),
			["BT_BUFF_LAUNCHER"] = new BT_BUFF_LAUNCHERTypeParser(),
			["BT_CLOAK_LAUNCHER"] = new BT_CLOAK_LAUNCHERTypeParser(),
			["BT_EFFECT_LAUNCHER"] = new BT_EFFECT_LAUNCHERTypeParser(),
			["BT_FANCY_LAUNCH"] = new BT_FANCY_LAUNCHTypeParser(),
			["BT_FIREBALL_DATA"] = new BT_FIREBALL_DATATypeParser(),
			["BT_JUMP_LAUNCHER"] = new BT_JUMP_LAUNCHERTypeParser(),
			["BT_MOON_RESOURCE_LAUNCHER"] = new BT_MOON_RESOURCE_LAUNCHERTypeParser(),
			["BT_MULTICLOAK_LAUNCHER"] = new BT_MULTICLOAK_LAUNCHERTypeParser(),
			["BT_NOVA_LAUNCHER"] = new BT_NOVA_LAUNCHERTypeParser(),
			["BT_PING_LAUNCHER"] = new BT_PING_LAUNCHERTypeParser(),
			["BT_RECON_LAUNCH"] = new BT_RECON_LAUNCHTypeParser(),
			["BT_REPAIR_LAUNCHER"] = new BT_REPAIR_LAUNCHERTypeParser(),
			["BT_WORMHOLE_LAUNCHER"] = new BT_WORMHOLE_LAUNCHERTypeParser(),
			["BT_AEBOLT_DATA"] = new BT_AEBOLT_DATATypeParser(),
			["BT_AEGIS_DATA"] = new BT_AEGIS_DATATypeParser(),
			["BT_ANIMOBJ_DATA"] = new BT_ANIMOBJ_DATATypeParser(),
			["BT_ANTIMATTER_DATA"] = new BT_ANTIMATTER_DATATypeParser(),
			["BT_ARC_DATA"] = new BT_ARC_DATATypeParser(),
			["BT_ASTEROIDFIELD_DATA"] = new BT_ASTEROIDFIELD_DATATypeParser(),
			["BT_DESTABILIZER_DATA"] = new BT_DESTABILIZER_DATATypeParser(),
			["BT_DUMBRECONPROBE_DATA"] = new BT_DUMBRECONPROBE_DATATypeParser(),
			["BT_ENGINETRAIL"] = new BT_ENGINETRAILTypeParser(),
			["BT_EXTENSION_INFO"] = new BT_EXTENSION_INFOTypeParser(),
			["BT_GATTLINGBEAM_DATA"] = new BT_GATTLINGBEAM_DATATypeParser(),
			["BT_MASS_DISRUPTOR_DATA"] = new BT_MASS_DISRUPTOR_DATATypeParser(),
			["BT_MESH_EXPLOSION"] = new BT_MESH_EXPLOSIONTypeParser(),
			["BT_MIMIC_DATA"] = new BT_MIMIC_DATATypeParser(),
			["BT_MINEFIELD_DATA"] = new BT_MINEFIELD_DATATypeParser(),
			["BT_NEBULA_DATA"] = new BT_NEBULA_DATATypeParser(),
			["BT_NOVA_EXPLOSION"] = new BT_NOVA_EXPLOSIONTypeParser(),
			["BT_PARTICLE_CIRCLE"] = new BT_PARTICLE_CIRCLETypeParser(),
			["BT_PARTICLE_DATA"] = new BT_PARTICLE_DATATypeParser(),
			["BT_PKBOLT_DATA"] = new BT_PKBOLT_DATATypeParser(),
			["BT_PLASMABOLT_DATA"] = new BT_PLASMABOLT_DATATypeParser(),
			["BT_REPELLENTCLOUD_DATA"] = new BT_REPELLENTCLOUD_DATATypeParser(),
			["BT_REPULSOR_DATA"] = new BT_REPULSOR_DATATypeParser(),
			["BT_REPULSORWAVE_DATA"] = new BT_REPULSORWAVE_DATATypeParser(),
			["BT_SPACEWAVE_DATA"] = new BT_SPACEWAVE_DATATypeParser(),
			["BT_STASISBOLT_DATA"] = new BT_STASISBOLT_DATATypeParser(),
			["BT_SYSTEM_BUFF_LAUNCHER"] = new BT_SYSTEM_BUFF_LAUNCHERTypeParser(),
			["BT_TALORIAN_EFFECT"] = new BT_TALORIAN_EFFECTTypeParser(),
			["BT_TEMPHQ_LAUNCHER"] = new BT_TEMPHQ_LAUNCHERTypeParser(),
			["BT_TRAIL_DATA"] = new BT_TRAIL_DATATypeParser(),
			["BT_BLACKHOLE_DATA"] = new BT_BLACKHOLE_DATATypeParser(),
			["BT_BUILDERSHIP_DATA"] = new BT_BUILDERSHIP_DATATypeParser(),
			["BT_FIGHTER_DATA"] = new BT_FIGHTER_DATATypeParser(),
			["BT_GUNBOAT_DATA"] = new BT_GUNBOAT_DATATypeParser(),
			["BT_HARVESTSHIP_DATA"] = new BT_HARVESTSHIP_DATATypeParser(),
			["BT_JUMPGATE_DATA"] = new BT_JUMPGATE_DATATypeParser(),
			["BT_LISTEN_ARTIFACT"] = new BT_LISTEN_ARTIFACTTypeParser(),
			["BT_MANTIS_BUILD"] = new BT_MANTIS_BUILDTypeParser(),
			["BT_MOVIE_CAMERA_DATA"] = new BT_MOVIE_CAMERA_DATATypeParser(),
			["BT_MINELAYER_DATA"] = new BT_MINELAYER_DATATypeParser(),
			["BT_NUGGET_DATA"] = new BT_NUGGET_DATATypeParser(),
			["BT_OBJECT_GENERATOR"] = new BT_OBJECT_GENERATORTypeParser(),
			["BT_PLANET_DATA"] = new BT_PLANET_DATATypeParser(),
			["BT_PLAYERBOMB_DATA"] = new BT_PLAYERBOMB_DATATypeParser(),
			["BT_PROJECTILE_DATA"] = new BT_PROJECTILE_DATATypeParser(),
			["BT_RECONPROBE_DATA"] = new BT_RECONPROBE_DATATypeParser(),
			["BT_STREAK_DATA"] = new BT_STREAK_DATATypeParser(),
			["BT_SUPPLYSHIP_DATA"] = new BT_SUPPLYSHIP_DATATypeParser(),
			["BT_SWAPPER_DATA"] = new BT_SWAPPER_DATATypeParser(),
			["BT_SYNTHESIS_DATA"] = new BT_SYNTHESIS_DATATypeParser(),
			["BT_TALORIAN_LAUNCHER"] = new BT_TALORIAN_LAUNCHERTypeParser(),
			["BT_TERRAFORM_ARTIFACT"] = new BT_TERRAFORM_ARTIFACTTypeParser(),
			["BT_TERRAN_BUILD"] = new BT_TERRAN_BUILDTypeParser(),
			["BT_TORPEDO_DATA"] = new BT_TORPEDO_DATATypeParser(),
			["BT_ZEALOT_DATA"] = new BT_ZEALOT_DATATypeParser(),
			["BT_ADMIRAL_RES"] = new BT_ADMIRAL_RESTypeParser(),
			["BT_ANMBOLT_DATA"] = new BT_ANMBOLT_DATATypeParser(),
			["BT_COMMAND_KIT"] = new BT_COMMAND_KITTypeParser(),
			["BT_FABRICATOR_DATA"] = new BT_FABRICATOR_DATATypeParser(),
			["BT_FIGHTER_WING"] = new BT_FIGHTER_WINGTypeParser(),
			["BT_FLAGSHIP_DATA"] = new BT_FLAGSHIP_DATATypeParser(),
			["BT_FORMATION"] = new BT_FORMATIONTypeParser(),
			["BT_GASHARVESTER_DATA"] = new BT_GASHARVESTER_DATATypeParser(),
			["BT_LASERSPRAY_DATA"] = new BT_LASERSPRAY_DATATypeParser(),
			["BT_MAP_GEN"] = new BT_MAP_GENTypeParser(),
			["BT_OVERDRIVE_DATA"] = new BT_OVERDRIVE_DATATypeParser(),
			["BT_PLAT_GUN"] = new BT_PLAT_GUNTypeParser(),
			["BT_PLAT_BUILD_DATA"] = new BT_PLAT_BUILD_DATATypeParser(),
			["BT_PLAT_BUILDSUP_DATA"] = new BT_PLAT_BUILDSUP_DATATypeParser(),
			["BT_PLAT_REFINE_DATA"] = new BT_PLAT_REFINE_DATATypeParser(),
			["BT_PLAT_REPAIR_DATA"] = new BT_PLAT_REPAIR_DATATypeParser(),
			["BT_PLAT_GENERAL_DATA"] = new BT_PLAT_GENERAL_DATATypeParser(),
			["BT_PLAT_SELL_DATA"] = new BT_PLAT_SELL_DATATypeParser(),
			["BT_PLAT_JUMP_DATA"] = new BT_PLAT_JUMP_DATATypeParser(),
			["BT_RECOVERYSHIP_DATA"] = new BT_RECOVERYSHIP_DATATypeParser(),
			["BT_RESEARCH"] = new BT_RESEARCHTypeParser(),
			["BT_SCRIPTOBJECT"] = new BT_SCRIPTOBJECTTypeParser(),
			["BT_SHIPLAUNCH"] = new BT_SHIPLAUNCHTypeParser(),
			["BT_SOLARIAN_BUILD"] = new BT_SOLARIAN_BUILDTypeParser(),
			["BT_SPECIALBOLT_DATA"] = new BT_SPECIALBOLT_DATATypeParser(),
			["BT_TRACTOR_DATA"] = new BT_TRACTOR_DATATypeParser(),
			["BT_TRACTOR_WAVE_LAUNCHER"] = new BT_TRACTOR_WAVE_LAUNCHERTypeParser(),
			["BT_TRIGGER"] = new BT_TRIGGERTypeParser(),
			["BT_TROOPPOD_DATA"] = new BT_TROOPPOD_DATATypeParser(),
			["BT_TROOPSHIP_DATA"] = new BT_TROOPSHIP_DATATypeParser(),
			["BT_TURRET"] = new BT_TURRETTypeParser(),
			["BT_UI_ANIM"] = new BT_UI_ANIMTypeParser(),
			["BT_UPGRADE"] = new BT_UPGRADETypeParser(),
			["BT_VERTICAL_LAUNCH"] = new BT_VERTICAL_LAUNCHTypeParser(),
			["BT_WAYPOINT"] = new BT_WAYPOINTTypeParser(),
			["BT_WORMHOLE_EFFECT"] = new BT_WORMHOLE_EFFECTTypeParser(),
			["GT_FONT"] = new GT_FONTTypeParser(),
			["GT_BUTTON"] = new GT_BUTTONTypeParser(),
			["GT_STATIC"] = new GT_STATICTypeParser(),
			["GT_EDIT"] = new GT_EDITTypeParser(),
			["GT_LISTBOX"] = new GT_LISTBOXTypeParser(),
			["GT_SCROLLBAR"] = new GT_SCROLLBARTypeParser(),
			["GT_PROGRESS_STATIC"] = new GT_PROGRESS_STATICTypeParser(),
			["GT_DROPDOWN"] = new GT_DROPDOWNTypeParser(),
			["GT_COMBOBOX"] = new GT_COMBOBOXTypeParser(),
			["GT_QUEUECONTROL"] = new GT_QUEUECONTROLTypeParser(),
			["GT_ICON"] = new GT_ICONTypeParser(),
			["GT_HOTBUTTON"] = new GT_HOTBUTTONTypeParser(),
			["GT_HOTSTATIC"] = new GT_HOTSTATICTypeParser(),
			["GT_TABCONTROL"] = new GT_TABCONTROLTypeParser(),
			["GT_SLIDER"] = new GT_SLIDERTypeParser(),
			["GT_DIPLOMACYBUTTON"] = new GT_DIPLOMACYBUTTONTypeParser(),
			["GT_SHIPSILBUTTON"] = new GT_SHIPSILBUTTONTypeParser(),
			["GT_ANIMATE"] = new GT_ANIMATETypeParser(),
			["GT_VFXSHAPE"] = new GT_VFXSHAPETypeParser(),
			["GT_MESSAGEBOX"] = new GT_MESSAGEBOXTypeParser(),
			["GT_MOVIESCREEN"] = new GT_MOVIESCREENTypeParser(),
			["GT_BRIEFING"] = new GT_BRIEFINGTypeParser(),
			["GT_CHAT"] = new GT_CHATTypeParser(),
			["GT_CREDITS"] = new GT_CREDITSTypeParser(),
			["GT_DIPLOMACYMENU"] = new GT_DIPLOMACYMENUTypeParser(),
			["GT_ENDGAME"] = new GT_ENDGAMETypeParser(),
			["GT_GLOBAL_SOUNDS"] = new GT_GLOBAL_SOUNDSTypeParser(),
			["GT_GLOBAL_VALUES"] = new GT_GLOBAL_VALUESTypeParser(),
			["GT_IGOPTIONS"] = new GT_IGOPTIONSTypeParser(),
			["GT_LOADSAVE"] = new GT_LOADSAVETypeParser(),
			["GT_MAPSELECT"] = new GT_MAPSELECTTypeParser(),
			["GT_MENU1"] = new GT_MENU1TypeParser(),
			["GT_MENUOBJECTIVES"] = new GT_MENUOBJECTIVESTypeParser(),
			["GT_NEWPLAYER"] = new GT_NEWPLAYERTypeParser(),
			["GT_OPTIONS"] = new GT_OPTIONSTypeParser(),
			["GT_PAUSE"] = new GT_PAUSETypeParser(),
			["GT_PLAYERCHATMENU"] = new GT_PLAYERCHATMENUTypeParser(),
			["GT_SPECIALABILITIES"] = new GT_SPECIALABILITIESTypeParser(),
			["GT_SYSTEM_KIT"] = new GT_SYSTEM_KITTypeParser(),
			["GT_SYSTEM_KIT_SAVELOAD"] = new GT_SYSTEM_KIT_SAVELOADTypeParser(),
			["GT_TOOLBAR"] = new GT_TOOLBARTypeParser()
		};

	public static readonly IReadOnlyList<string> First20ImplementationOrder = [
		"MT_STRINGPACK",
		"MT_UNITSPEECH",
		"BT_GROUP",
		"BT_LIGHT",
		"GT_FONT",
		"GT_BUTTON",
		"GT_STATIC",
		"GT_EDIT",
		"GT_LISTBOX",
		"GT_SCROLLBAR",
		"GT_PROGRESS_STATIC",
		"GT_DROPDOWN",
		"GT_COMBOBOX",
		"GT_QUEUECONTROL",
		"GT_ICON",
		"GT_HOTBUTTON",
		"GT_HOTSTATIC",
		"GT_TABCONTROL",
		"GT_SLIDER",
		"GT_DIPLOMACYBUTTON"
	];
}
