<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ConquestFrontierWarsRay</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
    <PackageId>ConquestFrontierWars</PackageId>
    <ApplicationIcon>..\..\assets\cur\Icon1.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.UI\Core.UI.csproj" />
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Framework\Framework.csproj" />
    <ProjectReference Include="..\Gloabls\Gloabls.csproj" />
    <ProjectReference Include="..\Math3D\Math3D.csproj" />
    <ProjectReference Include="..\Runtime.Collision\Runtime.Collision.csproj" />
    <ProjectReference Include="..\Windowing\Windowing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\assets\cur\Icon1.ico">
      <Link>Assets\cur\Icon1.ico</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\assets\Fonts\**\*">
      <Link>Fonts\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\assets\Movies\**\*">
      <Link>Assets\Movies\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\conquest_frontier_wars_ost\**\*">
      <Link>conquest_frontier_wars_ost\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
