<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>ConquestFrontierWarsRay</RootNamespace>
    <AssemblyName>ConquestFrontierWarsRay</AssemblyName>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConquestFrontierWarsRay.Math3D\ConquestFrontierWarsRay.Math3D.csproj" />
    <ProjectReference Include="..\ConquestFrontierWarsRay.Runtime.Collision\ConquestFrontierWarsRay.Runtime.Collision.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Fonts\**\*">
      <Link>Fonts\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\conquest_frontier_wars_ost\**\*">
      <Link>conquest_frontier_wars_ost\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
